SELECT ROUND(SUM(SALES_VALUE),0)AS TOTAL_SALES,
SUM(QUANTITY) AS TOTAL_ITEMS,
COUNT(DISTINCT BASKET_ID)AS TOTAL_TRANSACTIONS,
ROUND(SUM(SALES_VALUE)/COUNT(DISTINCT BASKET_ID),2)AS AVG_BASKET_VALUE
FROM TRANSACTIONS_DATA; 


SELECT PRODUCT_ID,
ROUND(SUM(SALES_VALUE),0) AS TOTAL_SALES
FROM TRANSACTIONS_DATA
GROUP BY PRODUCT_ID 
ORDER BY TOTAL_SALES DESC
LIMIT 10;

SELECT P.BRAND,
ROUND(SUM(T.SALES_VALUE),0) AS TOTAL_SALES
FROM TRANSACTIONS_DATA T
JOIN PRODUCTS P ON T.PRODUCT_ID = P.PRODUCT_ID 
GROUP BY P.BRAND 
ORDER BY TOTAL_SALES DESC;

SELECT CASE WHEN C.DISPLAY = 0 THEN 'NO_DISPLAY' ELSE 'DISPLAY'
END AS DISPLAY_FLAG,
ROUND(AVG(T.QUANTITY),2) AS AVG_QTY,
ROUND(AVG(T.SALES_VALUE),2) AS AVG_SALES
FROM TRANSACTIONS_DATA T 
LEFT JOIN  CAUSAL_DATA C ON  T.PRODUCT_ID = C.PRODUCT_ID 
GROUP BY DISPLAY_FLAG;


SELECT C.DISPLAY,
ROUND(AVG(T.QUANTITY),2) AS AVG_QTY
FROM TRANSACTIONS_DATA T 
JOIN CAUSAL_DATA C ON T.PRODUCT_ID = C.PRODUCT_ID 
WHERE C.DISPLAY<>0 
GROUP BY C.DISPLAY
ORDER BY AVG_QTY DESC;


SELECT C.MAILER,
ROUND(AVG(T.SALES_VALUE),2) AS AVG_SALES
FROM TRANSACTIONS_DATA T 
LEFT JOIN CAUSAL_DATA C 
ON T.PRODUCT_ID = C.PRODUCT_ID 
GROUP BY C.MAILER;


SELECT CASE WHEN 
RETAIL_DISC <>0
OR COUPON_DISC <>0
OR COUPON_MATCH_DISC <>0
THEN 'DISCOUNT' ELSE 'NO_DISCOUNT'
END AS DISCOUNT_FLAG,
ROUND(AVG(QUANTITY),2) AS AVG_QTY,
ROUND(AVG(SALES_VALUE),2) AS AVG_SALES 
FROM TRANSACTIONS_DATA 
GROUP BY DISCOUNT_FLAG;


SELECT ROUND(SUM(SALES_VALUE)/ABS(SUM(RETAIL_DISC +COUPON_DISC + COUPON_MATCH_DISC)),2) 
AS SALES_TO_DISCOUNT_RATIO
FROM TRANSACTIONS_DATA 
WHERE RETAIL_DISC <>0
OR COUPON_DISC <>0 
OR COUPON_MATCH_DISC <>0;

SELECT D.CLASSIFICATION_1,
ROUND(SUM(T.SALES_VALUE),0) AS TOTAL_SALES,
ROUND(AVG(T.SALES_VALUE),2) AS AVG_SPEND 
FROM TRANSACTIONS_DATA T 
JOIN HH_DEMOGRAPHIC D ON T.HOUSEHOLD_KEY = D.HOUSEHOLD_KEY 
GROUP BY D.CLASSIFICATION_1
ORDER BY TOTAL_SALES DESC;


SELECT
D.KID_CATEGORY_DESC,
ROUND(AVG(T.QUANTITY),2) AS AVG_QTY,
ROUND(AVG(T.SALES_VALUE),2) AS AVG_SALES
FROM TRANSACTIONS_DATA T
JOIN HH_DEMOGRAPHIC D
  ON T.HOUSEHOLD_KEY = D.HOUSEHOLD_KEY
GROUP BY D.KID_CATEGORY_DESC;


SELECT
D.CLASSIFICATION_1,
CASE WHEN C.DISPLAY <> 0 THEN 'DISPLAY' ELSE 'NO_DISPLAY' END AS PROMO_FLAG,
ROUND(AVG(T.QUANTITY),2) AS AVG_QTY
FROM TRANSACTIONS_DATA T 
JOIN HH_DEMOGRAPHIC D
ON T.HOUSEHOLD_KEY = D.HOUSEHOLD_KEY
LEFT JOIN CAUSAL_DATA C
ON T.PRODUCT_ID = C.PRODUCT_ID
AND T.STORE_ID = C.STORE_ID
GROUP BY D.CLASSIFICATION_1, PROMO_FLAG;
